### PR TITLE
Update project.clj

### PR DESCRIPTION
**Pull request by mosfet80**
updated libraries

### CODE REVIEW

**Comment by phillord** [comment]
Not so convinced by this. It will update the minimum required version when earlier versions would also work. Is there a reason beyond the latest and greatest for this?

**Comment by mosfet80** [comment]
[**owlapi-distribution/4.5.19**](https://mvnrepository.com/artifact/net.sourceforge.owlapi/owlapi-distribution/4.5.19) have **24 vulvenarbilities**

**Comment by phillord-ncl** [comment]
Yes, that's an interesting question, whether the project.clj should represent the minimally required version, or the preferred version. If leiningen or clj expect semantic version to be followed, they might reasonably use these versions (but not OWL-API 5) anyway. But I don't know that they do.

**Comment by phillord-ncl** [comment]
Closing in favour of:

https://github.com/phillord/tawny-owl/commit/57f3913e83abbc460126880a5db2b2dbcbe2f555

Thanks for the PR!

**Comment by phillord** [comment]
I do dislike githubs handling of multiple accounts!

Really closing in favour of https://github.com/phillord/tawny-owl/commit/57f3913e83abbc460126880a5db2b2dbcbe2f555

**Pull request closed without merging**
